//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsudaKageyu.SimpleWebSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsudaKageyu.SimpleWebSearch.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to restore the default settings?.
        /// </summary>
        internal static string ConfirmRestoreDefault {
            get {
                return ResourceManager.GetString("ConfirmRestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Google for &apos;%QUERY%&apos;.
        /// </summary>
        internal static string DefaultCaption {
            get {
                return ResourceManager.GetString("DefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65001.
        /// </summary>
        internal static string DefaultCodePage {
            get {
                return ResourceManager.GetString("DefaultCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=%QUERY%&amp;ie=UTF-8&amp;hl=en&amp;lr=lang_en.
        /// </summary>
        internal static string DefaultURL {
            get {
                return ResourceManager.GetString("DefaultURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string DefaultUseBuiltInBrowser {
            get {
                return ResourceManager.GetString("DefaultUseBuiltInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Web Search.
        /// </summary>
        internal static string ExtensionTitle {
            get {
                return ResourceManager.GetString("ExtensionTitle", resourceCulture);
            }
        }
    }
}
